# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5791461bfc3e79087ab0625bac446e3f93aa83a863b3955c7b831d71806cfe8a3196e9c8e6e2efc76d17101870cdae040a6196bce28cd57353a100e6a4999bca

test:
  secret_key_base: 34a6d03b8de2fb417700da84bd050b765a5094e31925d1ca3fa8da3010ee6f044c01387449ac5cfe12cf724f55b8d782964bef21a4392ccf6680e748f6a5fc38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
